version: "3"

services:
  video-transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - LLM_HOST=http://ollama:11434/api/generate
      - LLM_MODEL=deepseek-r1
      - PYTHONUNBUFFERED=1 # Ensure Python output is not buffered
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama-data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/ollama-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s # Give time for the model to be pulled
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
