version: "3"

services:
  video-transcriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      - ollama
    environment:
      - LLM_HOST=http://ollama:11434/api/generate
      - LLM_MODEL=deepseek-r1
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama-data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/ollama-entrypoint.sh"]
