version: "3.8"

services:
  transcription-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcription-service-test
    volumes:
      - ../../data/videos:/app/data/videos
      - ./test_audio:/app/test_audio
      - ./test_results:/app/test_results
    environment:
      - VIDEO_DIRS=/app/data/videos,/app/test_audio
      - API_URL=http://localhost:8000 # Not used in standalone mode
      - PYTHONPATH=/app
    working_dir: /app
    command: python standalone_test.py
    # Override the default command to run our standalone test
    # You can also run: docker-compose -f docker-compose.standalone.yml run transcription-test python test_whisperx.py
